---
abstract: 'Implementation for the riap command-line shell'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  File::Spec: 0
  IO::Handle: 0
  IPC::Open3: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.001, CPAN::Meta::Converter version 2.132140'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-riap
requires:
  Data::Clean::JSON: 0.13
  Data::Sah: 0
  JSON: 0
  Log::Any: 0
  Path::Naive: 0.02
  Perinci::Access: 0.34
  Perinci::CmdLine: 0.94
  Perinci::Result::Format: 0
  Perinci::Sub::Complete: 0.34
  Perinci::Sub::GetArgs::Argv: 0.27
  Perinci::Sub::Wrapper: 0.46
  Riap: v1.1.19
  SHARYANTO::Complete::Util: 0
  Term::ReadLine::Perl: 0
  Term::Shell: 0
  URI: 0
  perl: 5.010001
version: 0.01
